##  "mock" o "json"
dao = json

## LOG ##
quarkus.log.console.enable = true
quarkus.console.color = true
quarkus.log.level = WARN
quarkus.log.category."it.unibas.inputdevicebridge".level = INFO
quarkus.log.console.format = %d{yyyy-MM-dd HH:mm:ss} %p %c{1.15} - %s%n